name : Data-Validate-Sanctions

on:
  schedule:
    - cron: 42 4 * * 1

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install module
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure --test --configure-timeout=1920 --no-retry Data::Validate::Sanctions
